### ISSUE TITLE
"Error while sending feedback"

### ISSUE THREAD

**Issue by Apptation** [freshdesk/mobihelp-ios#21]
Mobihelp configuration was working previously, and the FAQs are showing perfectly within the app.

But when a ticket is created, the error is displayed on the iOS screen: "Error while sending feedback", and the console log shows:

Failed to create ticket Error Domain=COM.FRESHDESK.MOBIHELP_ERROR_DOMAIN Code=9 "Default Error" UserInfo={NSLocalizedFailureReason=Default Error, NSLocalizedRecoverySuggestion=Something is not right. Unexpected Error encountered.}

The config is as basic as it gets - nothing is added from the default that is provided directly in the mobihelp admin settings for the app.

**Comment by Apptation** [comment]
You're right. It was because of testing with an internal email.

Hotline's price model costs 100x more than mobihelp. Maybe that's why it was created?

Switching to zendesk would be a whole lot less expensive of an option. Way less expensive.

Chris

**Comment by hrishikesh-p** [comment]
Chris , we can definitely work out the price for existing mobihelp customers. Please drop use an email @ support@hotline.io . We have a special pricing for existing mobihelp customers.

Hotline was created for a better mobile support experience and not to price it higher. You will see the value in it if you try it out.  

I am closing the issue here.

**Comment by Apptation** [comment]
Thanks

Chris
